liblcvm: protect policy behind ADD_POLICY
Tested:

(1) Default build:
```
$ git clone --recursive https://github.com/chemag/liblcvm liblcvm1
$ cd liblcvm1
$ mkdir build
$ cd build
$ CC=clang CXX=clang++ cmake -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_C_FLAGS_DEBUG="-g -O0" -DCMAKE_CXX_FLAGS_DEBUG="-g -O0" ..  # cmake with clang and debug/gdb symbols
...
$ make -j
...

$ make test
...
100% tests passed, 0 tests failed out of 70

Total Test time (real) =   0.21 sec

$ ./lcvm /tmp/a.mp4
infile,filesize,bitrate_bps,width,height,type,horizresolution,vertresolution,depth,chroma_format,bit_depth_luma,bit_depth_chroma,video_full_range_flag,colour_primaries,transfer_characteristics,matrix_coeffs,num_video_frames,frame_rate_fps_median,frame_rate_fps_average,frame_rate_fps_reverse_average,frame_rate_fps_stddev,video_freeze,audio_video_ratio,duration_video_sec,duration_audio_sec,timescale_video_hz,timescale_audio_hz,pts_duration_sec_average,pts_duration_sec_median,pts_duration_sec_stddev,pts_duration_sec_mad,frame_drop_count,frame_drop_ratio,normalized_frame_drop_average_length,frame_drop_length_percentile_50,frame_drop_length_percentile_90,frame_drop_length_consecutive_2,frame_drop_length_consecutive_5,num_video_keyframes,key_frame_ratio,audio_type,channel_count,sample_rate,sample_size
/tmp/a.mp4,83295646,634684.550179,1280.000000,720.000000,avc1,4718592,4718592,24,-1,-1,-1,0,1,1,1,31466,29.970030,29.982679,29.964484,0.012650,0,1.000020,1049.915533,1049.936689,90000,44100,0.033373,0.033367,0.000006,0.000000,0,0.000000,0.000000,0.000000,0.000000,0,0,243,129.489712,mp4a,2,44100,16
```

(2) Explicit ADD_POLICY=OFF
```
$ git clone --recursive https://github.com/chemag/liblcvm liblcvm2
$ cd liblcvm2
$ mkdir build
$ cd build
$ CC=clang CXX=clang++ cmake -DADD_POLICY=OFF -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_C_FLAGS_DEBUG="-g -O0" -DCMAKE_CXX_FLAGS_DEBUG="-g -O0" ..  # cmake with clang and debug/gdb symbols
$ make -j
...

$ make test
...
100% tests passed, 0 tests failed out of 70

Total Test time (real) =   0.22 sec

$ ./lcvm /tmp/a.mp4
infile,filesize,bitrate_bps,width,height,type,horizresolution,vertresolution,depth,chroma_format,bit_depth_luma,bit_depth_chroma,video_full_range_flag,colour_primaries,transfer_characteristics,matrix_coeffs,num_video_frames,frame_rate_fps_median,frame_rate_fps_average,frame_rate_fps_reverse_average,frame_rate_fps_stddev,video_freeze,audio_video_ratio,duration_video_sec,duration_audio_sec,timescale_video_hz,timescale_audio_hz,pts_duration_sec_average,pts_duration_sec_median,pts_duration_sec_stddev,pts_duration_sec_mad,frame_drop_count,frame_drop_ratio,normalized_frame_drop_average_length,frame_drop_length_percentile_50,frame_drop_length_percentile_90,frame_drop_length_consecutive_2,frame_drop_length_consecutive_5,num_video_keyframes,key_frame_ratio,audio_type,channel_count,sample_rate,sample_size
/tmp/a.mp4,83295646,634684.550179,1280.000000,720.000000,avc1,4718592,4718592,24,-1,-1,-1,0,1,1,1,31466,29.970030,29.982679,29.964484,0.012650,0,1.000020,1049.915533,1049.936689,90000,44100,0.033373,0.033367,0.000006,0.000000,0,0.000000,0.000000,0.000000,0.000000,0,0,243,129.489712,mp4a,2,44100,16
```

(3) Explicit ADD_POLICY=ON
```
$ git clone --recursive https://github.com/chemag/liblcvm liblcvm3
$ cd liblcvm3
$ mkdir build
$ cd build
$ CC=clang CXX=clang++ cmake -DADD_POLICY=ON -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_C_FLAGS_DEBUG="-g -O0" -DCMAKE_CXX_FLAGS_DEBUG="-g -O0" ..  # cmake with clang and debug/gdb symbols
$ make
...
[ 38%] Building CXX object CMakeFiles/liblcvm.dir/src/liblcvm.cc.o
In file included from liblcvm/src/liblcvm.cc:32:
In file included from liblcvm/include/policy_protovisitor.h:3:
liblcvm/autogen/protobuf-gen/rules.pb.h:14:10: fatal error: 'google/protobuf/runtime_version.h' file not found
   14 | #include "google/protobuf/runtime_version.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/liblcvm.dir/build.make:106: CMakeFiles/liblcvm.dir/src/liblcvm.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:760: CMakeFiles/liblcvm.dir/all] Error 2
make: *** [Makefile:101: all] Error 2
```

We need to fix this one.